In [2]:
import numpy as np

In [6]:
display(np)

<module 'numpy' from 'C:\\Users\\smc\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

# NUMPY ADD FUNCTION np.add(a,b)

In [4]:
a = 2+4
c = 3+4
b = np.add(a,c)

In [5]:
display(b)

13

# NUMPY SUBTRACT FUNCTION np.subtract(a,b)

In [9]:
a = 4+4
c = 3+4
b = np.subtract(a,c)

In [10]:
display(b)

1

# NUMPY NEGATIVE FUNCTION np.negative(a,b)

In [13]:
a = [1,2,4,5,6,3]
b = np.negative(a)

In [14]:
display(b)

array([-1, -2, -4, -5, -6, -3])

# NUMPY MULTIPLICATION FUNCTION np.multiply(a,b)

In [16]:
a = 3+4
c = 5+6
b = np.multiply(a,c)

In [17]:
display(b)

77

# NUMPY DIVIDE FUNCTION np.divide(a,b)

In [19]:
a = 3+4
c = 5+6
b = np.divide(c,a)

In [22]:
display(b)

1.5714285714285714

# NUMPY FLOOR_DIVIDE(no reminder) FUNCTION np.floor_divide(a,b)

In [23]:
a = 3+4
c = 5+6
b = np.floor_divide(c,a)

In [24]:
display(b)

1

In [25]:
NUMPY POWER FUNCTION np.power(a,b)

SyntaxError: invalid syntax (4192722040.py, line 1)

In [26]:
a = 3+4
c = 5+6
b = np.power(c,a)

In [29]:
display(b) # power raised as , from first param to the power of second param

19487171

# NUMPY MODULUS FUNCTION np.mod(a,b)

In [30]:
a = 3+4
c = 5+6
b = np.mod(c,a)

In [32]:
display(b)

4

In [ ]:
COMPUTE RECIPROCAL of EACH ARRAY

In [4]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.25      , 0.2       , 0.33333333, 0.16666667, 0.16666667])

# Array Arthmetic
Each of these arithmetic operations are simply convenient wrappers around specific functions built into NumPy for example, the + operator is a wrapper for the add function

In [5]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


# Use Absoulte Value
this Function Handle Complex Data ,return the Magnitude

In [6]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [7]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [8]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

# Trigonometry Functions

In [9]:
theta = np.linspace(0, np.pi, 3)
#theta represent angle ,by theta we can find specfic angle this method used for defining array of angle

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


# Inverse Trigonometric func

In [10]:
x = [-1, 0, 1]
#Inverse of Trigonometric Fucntion Inverse
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x)) # which is why values that should be zero do not always hit exactly zero

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


# EXPONENT & LOGARITHMS

In [11]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


# Inverse Exponents & Logs

In [13]:
#Inverse of This Exponent & Logarithms Fucntions
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [14]:
#For very Small Input which used in scientific Measurement
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


# Specialized Universal Func
NumPy has many more ufuncs available, including hyperbolic trig functions, bitwise arithmetic, comparison operators, conversions from radians to degrees, rounding and remainders, and much more. A look through the NumPy documentation reveals a lot of interesting functionality.

In [15]:
from scipy import special
# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


# Integral of Gaussian

In [17]:
# Error function (integral of Gaussian)
# its complement, and its inverse
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


# Outer Product

In [19]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

# Aggregates
For binary ufuncs, there are some interesting aggregates that can be computed directly from the object. For example, if we'd like to reduce an array with a particular operation, we can use the reduce method of any ufunc. A reduce repeatedly applies a given operation to the elements of an array until only a single result remains.

In [20]:
#For example, calling reduce on the add ufunc returns the sum of all elements in the array:

x = np.arange(1, 6)
np.add.reduce(x)

15

In [21]:
#Similarly, calling reduce on the multiply ufunc results in the product of all array elements:

np.multiply.reduce(x)

120

# Specifying Output
For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

In [22]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [24]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
